// <auto-generated />
using System;
using ArticleRegistration.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArticleRegistration.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ArticleRegistration.Api.Domain.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "IT",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Homelab",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Auto",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Vaerksted",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "El",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "VVS",
                            SortOrder = 60
                        });
                });

            modelBuilder.Entity("ArticleRegistration.Api.Domain.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnShoppingList")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypicalLocation")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Name");

                    b.HasIndex("Status", "IsOnShoppingList", "ArticleType");

                    b.ToTable("Articles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AreaId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ArticleType = "Stock",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = true,
                            Name = "RJ45 stik CAT6",
                            Note = "Pose med stik til terminering af kabler.",
                            Quantity = 0m,
                            ShoppingNote = "Koeb ny pose med mindst 25 stk",
                            Status = "Active",
                            TypicalLocation = "Sortimentskasse A3",
                            Unit = "stk",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AreaId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ArticleType = "Stock",
                            CreatedAtUtc = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = false,
                            Name = "Patchkabel CAT6 0.5m",
                            Quantity = 6m,
                            Status = "Active",
                            TypicalLocation = "Kabelkasse",
                            Unit = "stk",
                            UpdatedAtUtc = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AreaId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ArticleType = "Standard",
                            Brand = "Dell",
                            CreatedAtUtc = new DateTime(2026, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = false,
                            Model = "OptiPlex 7070 Micro",
                            Name = "Dell OptiPlex 7070 Micro",
                            Note = "Bruges som Proxmox node i homelab.",
                            Status = "Active",
                            TypicalLocation = "Rack hylde 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AreaId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ArticleType = "Stock",
                            Brand = "Samsung",
                            CreatedAtUtc = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = false,
                            Model = "PM883",
                            Name = "Samsung PM883 1.92TB SSD",
                            Note = "Ekstra SSD til homelab og testservere.",
                            Quantity = 2m,
                            Status = "Active",
                            TypicalLocation = "ESD kasse",
                            Unit = "stk",
                            UpdatedAtUtc = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AreaId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ArticleType = "Stock",
                            CreatedAtUtc = new DateTime(2026, 1, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = true,
                            Name = "Motorolie 5W-30 5L",
                            Note = "Passer til Renault Kadjar 1.3 TCe.",
                            Quantity = 0m,
                            ShoppingNote = "Husk OEM-specifikation RN17",
                            Status = "Active",
                            TypicalLocation = "Garagehylde",
                            Unit = "dunk",
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            AreaId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ArticleType = "Standard",
                            Brand = "Renault",
                            CreatedAtUtc = new DateTime(2026, 1, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = false,
                            Model = "17 tommer",
                            Name = "Renault Kadjar alufaelge 17 tommer",
                            Note = "Originalt sommerhjulsaet.",
                            Status = "Active",
                            TypicalLocation = "Garageloft",
                            UpdatedAtUtc = new DateTime(2026, 1, 6, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            AreaId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ArticleType = "Stock",
                            CreatedAtUtc = new DateTime(2026, 1, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = false,
                            Name = "Torx bits T20",
                            Note = "Loese bits til hurtig udskiftning.",
                            Quantity = 4m,
                            Status = "Active",
                            TypicalLocation = "Bitskuffe",
                            Unit = "stk",
                            UpdatedAtUtc = new DateTime(2026, 1, 7, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            AreaId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ArticleType = "Standard",
                            Brand = "Milwaukee",
                            CreatedAtUtc = new DateTime(2026, 1, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = false,
                            Model = "M12",
                            Name = "Milwaukee M12 boreskruemaskine",
                            Note = "Kompakt maskine til let montage.",
                            Status = "Archived",
                            TypicalLocation = "Vaerktoejsskab",
                            UpdatedAtUtc = new DateTime(2026, 1, 8, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            AreaId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ArticleType = "Stock",
                            Brand = "Wago",
                            CreatedAtUtc = new DateTime(2026, 1, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = false,
                            Model = "221-413",
                            Name = "Wago 221-413",
                            Note = "3-leder samlemuffer til standard elarbejde.",
                            Quantity = 18m,
                            Status = "Active",
                            TypicalLocation = "Elkasse",
                            Unit = "stk",
                            UpdatedAtUtc = new DateTime(2026, 1, 9, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            AreaId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ArticleType = "Stock",
                            CreatedAtUtc = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOnShoppingList = false,
                            Name = "PTFE tape 12mm",
                            Note = "Bruges ved mindre VVS-opgaver.",
                            Quantity = 3m,
                            Status = "Active",
                            TypicalLocation = "VVS kasse",
                            Unit = "rulle",
                            UpdatedAtUtc = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ArticleRegistration.Api.Domain.ArticleTag", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTags", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TagId = new Guid("aaaaaaaa-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TagId = new Guid("aaaaaaaa-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TagId = new Guid("aaaaaaaa-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TagId = new Guid("bbbbbbbb-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            TagId = new Guid("aaaaaaaa-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            TagId = new Guid("aaaaaaaa-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            TagId = new Guid("aaaaaaaa-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            TagId = new Guid("aaaaaaaa-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            TagId = new Guid("aaaaaaaa-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            TagId = new Guid("aaaaaaaa-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            TagId = new Guid("aaaaaaaa-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TagId = new Guid("aaaaaaaa-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TagId = new Guid("aaaaaaaa-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TagId = new Guid("bbbbbbbb-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000006"),
                            TagId = new Guid("aaaaaaaa-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000007"),
                            TagId = new Guid("aaaaaaaa-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000007"),
                            TagId = new Guid("bbbbbbbb-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000008"),
                            TagId = new Guid("aaaaaaaa-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000009"),
                            TagId = new Guid("bbbbbbbb-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000009"),
                            TagId = new Guid("bbbbbbbb-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000010"),
                            TagId = new Guid("bbbbbbbb-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ArticleId = new Guid("10000000-0000-0000-0000-000000000010"),
                            TagId = new Guid("bbbbbbbb-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("ArticleRegistration.Api.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Name = "netvaerk"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Name = "cat6"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Name = "rj45"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            Name = "homelab"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-5555-5555-5555-555555555555"),
                            Name = "server"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-6666-6666-6666-666666666666"),
                            Name = "storage"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-777777777777"),
                            Name = "olie"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-8888-8888-8888-888888888888"),
                            Name = "renault"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-9999-9999-9999-999999999999"),
                            Name = "vaerktoej"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Name = "el"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Name = "vvs"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Name = "forbrug"
                        });
                });

            modelBuilder.Entity("ArticleRegistration.Api.Domain.Article", b =>
                {
                    b.HasOne("ArticleRegistration.Api.Domain.Area", "Area")
                        .WithMany("Articles")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("ArticleRegistration.Api.Domain.ArticleTag", b =>
                {
                    b.HasOne("ArticleRegistration.Api.Domain.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArticleRegistration.Api.Domain.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ArticleRegistration.Api.Domain.Area", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("ArticleRegistration.Api.Domain.Article", b =>
                {
                    b.Navigation("ArticleTags");
                });

            modelBuilder.Entity("ArticleRegistration.Api.Domain.Tag", b =>
                {
                    b.Navigation("ArticleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
